name: Build HHKungfu CloudStream

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '7.4.2'

      - name: Build HHKungfu
        run: |
          gradle HHKungfu:make --no-daemon --stacktrace

      - name: Find CS3
        run: |
          mkdir -p artifacts
          find . -type f -name "*.cs3" -exec cp {} artifacts/ \;

      - name: Upload HHKungfu.cs3
        uses: actions/upload-artifact@v4
        with:
          name: HHKungfu
          path: artifacts/
